### ISSUE TITLE
Permission denied: Github releases deployment

### ISSUE THREAD

**Issue by chrisnharvey** [travis-ci/dpl#488] opened 2016-08-01 16:28 UTC
Hi,

I'm using travis-ci to deploy the eloquentos/packages build ourput to Github releases, but I can't seem it get it working as I keep getting the following error(s).

```bash
error: could not lock config file .git/config: Permission denied
error: could not lock config file .git/config: Permission denied
No stash found.
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - .dpl (Errno::EACCES)
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `each'
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/provider.rb:128:in `deploy'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:32:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/lib/dpl/cli.rb:7:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.17/bin/dpl:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by BanzaiMan** [comment] 2016-08-01 17:30
Duplicate of https://github.com/travis-ci/travis-ci/issues/6397

**Closed by BanzaiMan** 2016-08-01 17:30 UTC
