### ISSUE TITLE
[Github Releases] Error when editing a release

### ISSUE THREAD

**Issue by cedricziel** [travis-ci/dpl#846] opened 2018-08-01 10:24 UTC
My project deploys to Gihub releases. It does so, from two different builds, because, you know, different platform. What happened until now: One build creates the release, another one amends an artifact.

This worked fine, until today (maybe 4 days since the last release).

The build: https://travis-ci.org/cedricziel/idea-php-typo3-plugin/jobs/410734265#L781

It seems the Github API is blocking the operation. Because the validation failed (code: `already_exists`)

Is there any option I should use now? `overwrite` only seems to apply to the artifacts being pushed.

**Comment by slodki** [comment] 2018-09-30 22:30
This is problem with uploading file:
```
Error summary:
  resource: ReleaseAsset
  code: already_exists
```
duplicate of #821 IMHO - you have some chars in filename replaced with dot...

**Comment by slodki** [comment] 2018-12-30 10:37
still not working

**Comment by svenfuchs** [comment] 2019-09-11 15:00
@cedricziel @slodki would you be able to confirm if this issue still exists in dpl v2 (current master, dev preview release, see https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release). 

in order to use this version you can opt in using

```yaml
deploy:
  - provider: releases
    edge: true
    ...
```

you should be able to control this with the option `overwrite` https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/releases.rb#L26 

i am guessing there still is a race condition where we read assets first, and then decide how to deal with existing assets later, while in the meantime another job may have pushed them (or there might be delay on GitHub's side) ... but it would be good to be able reproduce this

**Comment by proddy** [comment] 2019-10-22 19:07
I have the same issue, using dpl v2 trying to overwrite existing assets when releasing to GitHub. First time is fine.

```yaml
deploy:
  provider: releases
  edge: true
  api_key: ${GITHUB_TOKEN} 
  file_glob: true
  file: firmware/files*.bin
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    branch: dev
    repo: proddy/testproject
```

and seeing

```
files1.bin: 422 - Validation Failed
Error summary:
  resource: ReleaseAsset
  code: already_exists
  field: name // See: https://developer.github.com/v3 (Octokit::UnprocessableEntity)
failed to deploy
```

**Comment by svenfuchs** [comment] 2019-10-24 20:35
@proddy could you please send URLs for build logs where you have seen this? if this is from a private repository, feel free to send them to support@travis-ci.org (and mention my name)

**Comment by proddy** [comment] 2019-10-24 20:43
@svenfuchs it's at https://travis-ci.com/proddy/EMS-ESP-CI 

the Travis script is used to build the files and I'm manually setting the tag and forcing the commit in the `before_deploy` with `git tag -f $TRAVIS_TAG`. 

The idea is to create nightly firmware builds via a CRON job to the same GitHub release and overwriting the tags and assets.

**Comment by svenfuchs** [comment] 2019-10-28 16:50
@proddy thanks for the URL and the extra input. the last build on `master` is green right now, and doesn't seem to have a failing deployment.

hmmm, i haven't been able to reproduce this. https://github.com/travis-ci/dpl_test/releases/tag/v0.0.0 has been published several times with the exact same assets. each time the log said `File dpl_test.rb already exists, overwriting` ... as expected.

am i misunderstanding the case?

if i am not missing something else i could see two ways your issue has been caused:

either there's a race condition in place where multiple jobs run deployments at the exact same time, but you do not even have a build matrix with multiple jobs per build in place. also, even if you had, it seems highly unlikely that this would happen each time then, unless your files are massive and take several minutes to upload, or something.

or this is an issue with GitHub's renaming of filenames. `dpl` does not do the same thing (yet), and i believe this causes failing uploads because `dpl` is not able to delete the asset first.

is there any chance you have unusual characters in the respective asset file names?

**Comment by proddy** [comment] 2019-10-28 17:44
Thanks @svenfuchs for looking into this. I had actually cleaned up the Releases in GitHub this morning so you wouldn't have seen the broken build! I've also changed to a single job (no more parallel builds) and restricted it to one asset to help pin-point the root cause.

I've just re-started the build and you'll see it fail (https://travis-ci.com/proddy/EMS-ESP-CI/builds/133732573). And it partially created a new release in the GitHub repo (https://github.com/proddy/EMS-ESP-CI/releases) but stopped when uploading the asset.

build error is:

```
POST https://uploads.github.com/repos/proddy/EMS-ESP-CI/releases/21021791/assets?name=EMS-ESP-1.9.2b9-d1_mini.bin: 422 - Validation Failed
Error summary:
  resource: ReleaseAsset
  code: already_exists
  field: name // See: https://developer.github.com/v3 (Octokit::UnprocessableEntity)
failed to deploy
```

**Comment by svenfuchs** [comment] 2019-10-28 18:50
@proddy i see, yes, it failed.

it looks like you've deleted the release on GitHub's side, could that be? the api returns an empty array for your repo. that makes it hard to inspect what's going on.

could you start an new build with the branch `sf-releases`? that should output a bunch of debug info. also, please keep the release on GitHub for the time being, if possible.

```yaml
deploy:
- provider: releases
  edge: 
    branch: sf-releases
```

**Comment by proddy** [comment] 2019-10-28 21:38
I've been trying different things and think I found a way to make it work. If I change `file` in the deploy from
```
file: "firmware/*.bin"
```
to

```
file: "*.bin"
```

and obviously make sure the .bin files are created in a directory higher, then it works each time.

**Comment by svenfuchs** [comment] 2019-10-29 14:55
@proddy woha, is that how GitHub releases work? when you upload a file `path/to/file.ext` then it ends up being listed as just `file.ext`?

if that is so then i think the code is not stripping the `path/to` bit when trying to detect the asset.

**Comment by svenfuchs** [comment] 2019-10-29 15:41
this finally reproduces the issue https://travis-ci.com/travis-ci/dpl/builds/134021676 (after moving the asset to a subdir)

and this fixes it: https://github.com/travis-ci/dpl/pull/1130

@proddy @cedricziel this is currently unreleased, if you want to test it out you can use master:

```yaml
deploy:
- provider: releases
  edge: 
    branch: master
```

i am going to close this issue here for now. please feel free to reopen it if needed.

**Closed by svenfuchs** 2019-10-29 15:41 UTC
Labels: important, provider: releases (GitHub Releases)

**Comment by proddy** [comment] 2019-10-29 17:04
thanks for the quick fix.
