### ISSUE TITLE
Unable to push on gh-pages

### ISSUE THREAD

**Issue by ldez** [travis-ci/dpl#771] opened 2018-03-09 13:23 UTC
Since the deployment of 1.9, the gh-pages provider is broken.

```
Couldn't push the build to github.com/containous/traefik.git:gh-pages
```

https://travis-ci.org/containous/traefik/builds/351290353

**Comment by BanzaiMan** [comment] 2018-03-09 13:32
Closing as a duplicate of #767, which itself is a duplicate of https://github.com/travis-ci/travis-ci/issues/9312.

**Closed by BanzaiMan** 2018-03-09 13:32 UTC
