### ISSUE TITLE
Deployment to GitHub pages fails

### ISSUE THREAD

**Issue by Klooven** [travis-ci/dpl#775] opened 2018-03-11 09:12 UTC
I've been trying to deploy files from a directory that is created during build to GitHub pages.

I've tried to run the build a few times (it fails always), and I'm using the same setup as I'm using in another repository where everything works fine.

Here's the error i get when the deploy starts:

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `mkdir': File exists @ dir_s_mkdir - /tmp/d20180311-4387-g2auc6/work (Errno::EEXIST)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:142:in `github_pull_or_init'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:196:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-pages-1.9.0/lib/dpl/provider/pages.rb:191:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

Here's the full build log: https://travis-ci.org/Tutrox/PihkalaToday/builds/351912914

Also for reference, here's my Travis config: https://github.com/Tutrox/PihkalaToday/blob/master/.travis.yml

_Please tell me if you need any clearification from my side!_

### UPDATE

Now getting the same error on a project that worked a few days ago (only thing changed was the `README.md` file in the repo).

Log: https://travis-ci.org/Tutrox/Mol/builds/351920259

**Comment by BanzaiMan** [comment] 2018-03-11 12:23
Duplicate of travis-ci/travis-ci#9312.

**Closed by BanzaiMan** 2018-03-11 12:23 UTC
