### ISSUE TITLE
CloudFiles provider missing gem

### ISSUE THREAD

**Issue by rgbkrk** [travis-ci/dpl#369] opened 2015-11-24 21:24 UTC
```
Deploying application
[fog][WARNING] 'mime-types' missing, please install and try again.
failed to deploy
```

**Comment by BanzaiMan** [comment] 2015-11-24 22:01
Could you point to a build log URL that shows this problem?

**Comment by rgbkrk** [comment] 2015-11-24 23:49
https://travis-ci.org/getcarina/dvm/builds/92976248

**Comment by BanzaiMan** [comment] 2015-11-25 01:05
Thanks. I'll close this as a duplicate of https://github.com/travis-ci/travis-ci/issues/5165 (in the main issues repo).

**Closed by BanzaiMan** 2015-11-25 01:05 UTC
