### ISSUE TITLE
Allow a user to set a EB version label in the travis YAML

### ISSUE THREAD

**Issue by LorneCurrie** [travis-ci/dpl#862] opened 2018-08-30 23:10 UTC
Currently, ELASTIC_BEANSTALK_LABEL is set as an env variable but would be good to allow a user to set the ELASTIC_BEANSTALK_LABEL as an option in the in the deploy provider.

**Comment by BanzaiMan** [comment] 2018-09-13 14:39
Duplicate of #859.

**Closed by BanzaiMan** 2018-09-13 14:39 UTC
