### ISSUE TITLE
Build not playing well faraday version bump?

### ISSUE THREAD

**Issue by NapsterInBlue** [travis-ci/dpl#1108] opened 2019-09-27 18:10 UTC
Hey all,

I keep a running `gh-pages` [repo of technical notes](https://github.com/NapsterInBlue/notes) that I've been building out for some time now.

[Pushed a build yesterday that worked great](https://travis-ci.org/NapsterInBlue/notes/builds/590086362#L997), but revisiting it today, I've been getting emails warning about [build failures](https://travis-ci.org/NapsterInBlue/notes/builds/590519498#L1000)

Examining, this happens at the final `Installing deploy dependencies` step and the only difference is that `faraday` got a version bump from `0.15.4` to `0.16.0`, which looks brand-spankin' new [as of today](https://rubygems.org/gems/faraday/versions). Having trouble making heads or tails on the error message, though

```
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.16.0
Successfully installed public_suffix-3.0.3
Successfully installed addressable-2.7.0
Successfully installed sawyer-0.8.2
Successfully installed octokit-4.6.2
Successfully installed dpl-pages-1.10.12
7 gems installed
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/default.rb:1:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit.rb:4:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-pages-1.10.12/lib/dpl/provider/pages.rb:1:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'

```

Is this something I can resolve on my end?

[Link to the simple `travis.yml` that kicks off the build](https://github.com/NapsterInBlue/notes/blob/master/.travis.yml)

Thank you!

**Comment by BanzaiMan** [comment] 2019-09-27 18:13
The error appears to be coming from Octokit's middleware.

https://github.com/octokit/octokit.rb/pull/1154

**Comment by NapsterInBlue** [comment] 2019-09-27 18:15
Will keep an eye on this!

Thanks for such a quick response-- I'm thoroughly out of my depth here, haha

**Comment by liyasthomas** [comment] 2019-09-27 18:22
Same here on my builds too. Deployment failing. Happened in last 1 or 2 hours. Before it was fine. Will keep an eye on here!

**Comment by ushis** [comment] 2019-09-27 18:53
@BanzaiMan A temporary quick fix for dpl could be adding `faraday <= 0.15.0` as dependency to the `dpl-releases.gemspec` until the issue is resolved in Octokit. Right?

**Comment by BanzaiMan** [comment] 2019-09-27 19:15
@ushis yes. Alternatively, you can install faraday before deployment starts (to the Ruby that runs deployment), but that feels like a hack, to be honest.

**Comment by BanzaiMan** [comment] 2019-09-27 19:31
Hello, everyone.

I've released [dpl-releases 1.10.13](https://rubygems.org/gems/dpl-releases/versions/1.10.13) and [dpl-pages 1.10.13](https://rubygems.org/gems/dpl-pages/versions/1.10.13) to address this problem.

Please rerun the affected builds and report the results.

Thanks.

**Comment by BanzaiMan** [comment] 2019-09-27 19:37
For completeness: https://github.com/lostisland/faraday/pull/1030

**Comment by StevenRacz** [comment] 2019-09-27 19:42
Fix is working for me. Thank you for the quick fix!

**Comment by NapsterInBlue** [comment] 2019-09-27 19:48
Same here! Huge thanks for taking the time to patch this :)

**Comment by ushis** [comment] 2019-09-27 19:53
@BanzaiMan Works. Thx a lot!

**Comment by davide-romanini** [comment] 2019-09-27 20:31
I'm using `edge:true` that uses `dpl-2.0.0.alpha.7.gem` and has the same problem.

**Comment by BanzaiMan** [comment] 2019-09-27 20:48
I'm inclined to wait for the upstream fixes for the edge. If it doesn't improve by early next week (say, Tuesday), we will consider amending it.

**Comment by liyasthomas** [comment] 2019-09-27 23:43
Issue has been fixed

**Comment by svenfuchs** [comment] 2019-10-01 17:18
For `v2` (`edge`) this had broken the end-to-end canary tests: https://travis-ci.com/travis-ci/dpl/builds/129558490 but has been fixed in the meantime: https://travis-ci.com/travis-ci/dpl/builds/129732505

I will assume this issue here can be closed. Please feel free to re-open it if needed.

**Closed by svenfuchs** 2019-10-01 17:18 UTC
