### ISSUE TITLE
S3 cache_control example does not work

### ISSUE THREAD

**Issue by rroncu** [travis-ci/dpl#679] opened 2017-08-18 11:54 UTC
When using `dpl --provider=s3 .... --cache_control="no-cache: index.html"` as shown in the README, the header that is received by the browser is `cache-control:no-cache: index.html`. 

I'm trying to achieve per file cache_control as shown in the spec at https://github.com/travis-ci/dpl/blob/master/spec/provider/s3_spec.rb#L108 but I can't find the cli syntax that will parse it correctly.

**Comment by BanzaiMan** [comment] 2017-12-15 20:19
Closing as a duplicate of #486.

**Closed by BanzaiMan** 2017-12-15 20:19 UTC
Labels: provider: s3
