### ISSUE TITLE
Packages not uploaded to PyPI: sh: 1: twine: not found

### ISSUE THREAD

**Issue by koterpillar** [travis-ci/dpl#299] opened 2015-08-07 11:36 UTC
In this build:

https://travis-ci.org/koterpillar/aloe/jobs/74553631

the package isn't being released to PyPI, and there is an error message in the log:

```
sh: 1: twine: not found
```

**Comment by zupo** [comment] 2015-08-12 11:36
I have the same issue. @koterpillar did you find any workarounds?

**Comment by koterpillar** [comment] 2015-08-12 11:51
My current workaround is to upload manually. I suppose installing `twine` manually would also be an option.

**Comment by zupo** [comment] 2015-08-12 11:56
Yeah but one cannot apt-get install when using ```sudo: false``` ...

**Comment by zupo** [comment] 2015-08-12 13:24
So, I did a bit of digging around and found the culprit.

First, one needs to install twine with ```pip install twine``` in ```before_deploy``` step. The deploy code runs OK then.

However it breaks where it calls twine if you do deploy to a custom PyPI server. The problem is how the ```~/.pypirc``` file is built and how `twine` is called.

The ```~/.pypirc``` file built by `dpl` is something like this: 

```
[distutils]
index-servers =
    pypi

[pypi]
repository: https://my.own.pypi.com/pypi
username: foo
password: bar
```

But when twine is called, `dpl` passes the ```#{options[:server] || 'pypi’}``` option, meaning it tells twine
to look for the ```https://my.own.pypi.com/pypi``` section. And there is only ```pypi``` section in the built ```~/.pypirc``` file.

So `dpl` should either build the ```~/.pypirc``` file in a way where the ```options[:server]``` is used for `index-servers` and the section title OR always call twine with ```-r ‘pypi’```. The latter option is probably simpler and hence, better.

**Comment by cotsog** [comment] 2015-08-14 20:45
We issued an intermediate fix for this.

In addition to manually install twine, you need to add `edge: true` to your `deploy:` section in your `.travis.yml` file:

    deploy:
      provider: pypi
      edge: true
      ...

Hope this helps.

**Comment by dhermes** [comment] 2015-08-14 21:09
Thanks for the fix. (Can you send a link to it?) What does `edge: true` do?

**Comment by BanzaiMan** [comment] 2015-08-17 18:37
@dhermes `edge: true` runs the deployment with the pre-release version that has a successful build (https://travis-ci.org/travis-ci/dpl/builds/75469158) until there is a release.

**Comment by BanzaiMan** [comment] 2015-08-17 19:05
I pushed to the `master` branch another commit, which aims to address the problem with the `twine` installation. Could any of you try deployment with `edge: true`, but without installing `twine` prior to the deployment?

**Comment by koterpillar** [comment] 2015-08-19 01:51
`edge: true`, without manually installing twine, worked for me just now.

2015-08-18 5:05 GMT+10:00 Hiro Asari <notifications@github.com>:

**Comment by BanzaiMan** [comment] 2015-08-19 12:35
Great! I've released 1.7.19. `edge: true` is no longer necessary.

**Closed by BanzaiMan** 2015-08-19 12:35 UTC
Labels: provider: pypi

**Comment by tlocke** [comment] 2016-05-24 10:42
This error seems to have recurred:

    sh: 1: twine: not found

I tried @zupo's fix:

    before_deploy:
        pip install twine

but this gives the error:

    pkginfo is in an unsupported or invalid wheel

Any help appreciated, thanks!

**Comment by fpagnoux** [comment] 2016-05-24 12:16
I have the same error: `sh: 1: twine: not found`.

**Comment by BanzaiMan** [comment] 2016-05-24 17:48
Sorry about the issue. Could you point us to a build log URL that shows the problem?

**Comment by tlocke** [comment] 2016-05-24 18:17
Yes it's at line 3678 at:

https://travis-ci.org/WessexWater/chellow/builds/132497112#L3678

Even though the build is green the deployment to PyPI failed.

**Comment by BanzaiMan** [comment] 2016-05-24 21:24
Thanks for the information. Whatever the regression is, I think the issue should be handled anew. Please open a new ticket.

**Comment by tlocke** [comment] 2016-05-24 21:49
As requested I've opened a new issue https://github.com/travis-ci/dpl/issues/453 for this.

**Comment by hermanbergwerf** [comment] 2016-06-29 11:55
I also failed to auto publish my package with the same error: https://travis-ci.org/hermanbergwerf/bashbeautify/builds/141048289#L245

**Comment by BanzaiMan** [comment] 2016-06-29 12:06
@hermanbergwerf Could you try rerunning the build? I think `pip install twine` might have failed for you for whatever reason.

**Comment by hermanbergwerf** [comment] 2016-06-29 12:14
I have retried the build several times, but I did not add `pip install twine`. Is that still required? It is not mentioned on https://docs.travis-ci.com/user/deployment/pypi.

**Comment by BanzaiMan** [comment] 2016-06-30 04:48
`pip install twine` is invoked by our utility.

I see the failure here: https://travis-ci.org/hermanbergwerf/bashbeautify/builds/141048289#L202.

I think this is a regression, so please open a new issue. Thanks.

**Comment by hermanbergwerf** [comment] 2016-06-30 05:51
See #470
