### ISSUE TITLE
Broken pipe (Faraday::ConnectionFailed) while uploading to GitHub Releases

### ISSUE THREAD

**Issue by slodki** [travis-ci/dpl#816] opened 2018-05-11 06:53 UTC
build log https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/377545718#L958
travis script https://github.com/moneymanagerex/moneymanagerex/blob/353395573dde163aa9165aa6cf6289c11e47e9eb/.travis.yml#L162
result:
```
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/openssl/buffering.rb:326:in `syswrite': Broken pipe (Faraday::ConnectionFailed)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:87:in `perform_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:38:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.15.1/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:138:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:119:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:109:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.6/lib/dpl/provider/releases.rb:109:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by iriberri** [comment] 2018-05-23 16:18
Hey there! I just stumbled upon this issue, and although I'm not sure of what could be causing this problem, I noticed that there was a new Faraday release ~40 minutes ago: https://github.com/lostisland/faraday/releases/tag/v0.15.2

I'm really curious to see if this new version could have fixed the issues you were seeing, or, otherwise discard that option. Could you please try restarting one of the affected builds or trigger a new one and let us know if you see the same error? Thank you!

**Comment by slodki** [comment] 2018-06-02 10:01
Travis is using Faraday 0.15.2 but problem still exists: https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/385957277#L952

**Comment by mlaccetti** [comment] 2018-06-12 18:20
Happening to me as well: https://travis-ci.org/mlaccetti/ipd2/builds/391396894

**Comment by slodki** [comment] 2018-09-10 19:26
still open

**Comment by BanzaiMan** [comment] 2018-09-30 15:05
Seems this is an intermittent problem. https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/435107383 https://travis-ci.org/mlaccetti/ipd2/builds/395006083

Perhaps we can add retries.

**Comment by BanzaiMan** [comment] 2018-11-15 19:51
Closing this as a duplicate of #229, which is a request for retry logic.

**Closed by BanzaiMan** 2018-11-15 19:51 UTC
Labels: provider: releases (GitHub Releases)
