### ISSUE TITLE
npm deploy only master branch

### ISSUE THREAD

**Issue by djindjic** [travis-ci/dpl#214] opened 2015-01-12 20:36 UTC
Am I doing something wrong if I make some changes on master branch in my github repo followed by this commands:
```bash
git add --all
git commit -m "update"
git tag v0.0.1
git push origin master
git push origin --tags
```

my .travis.yml is:
```yml
deploy:
  provider: npm
  email: me@email.com
  skip_cleanup: true
  api_key:
    secure: '...'
  on:
    tags: true
    repo: user/repo
```
It fails with `Skipping deployment with the npm provider because this branch is not permitted to deploy`, but am I just tagged latest commit on master branch? Why I need to include all_branches: true into configuration if I didn't make any new branch?

I have tried it with both annotated and lightweight tags described in [git docs](http://git-scm.com/book/en/v2/Git-Basics-Tagging#Creating-Tags) and had same problem.

I don't want to run travis build for other branches, especially in this case because when I push this commit and tag to github, travis starts two builds, one for commit and other for tag itself

**Comment by Joshua-Anderson** [comment] 2015-01-13 05:21
@djindjic Can you please link to a failing build?

**Comment by djindjic** [comment] 2015-01-13 08:43
here is my [build](https://travis-ci.org/djindjic/forwardablejs/builds/46827447).
If it matters, [here](https://github.com/djindjic/forwardablejs/blob/759e3abb7540cdcc39cccb2adef97d421e08f6f8/gulpfile.js#L8) is my gulp file which automate tagging and push to github.

**Comment by Joshua-Anderson** [comment] 2015-01-13 14:35
Hmm. What's strange is that 0.1.43 and 0.1.42 didn't get a tagged build, unlike 0.1.41, which is required to deploy. I'm not sure how that is happening unless you disabled them.

**Comment by djindjic** [comment] 2015-01-13 14:37
how do you think to disable them?

**Comment by djindjic** [comment] 2015-01-13 14:42
yes 0.1.43 is tagged commit, am I right?
commit message "0.1.43"
tag: "v0.1.43
https://github.com/djindjic/forwardablejs/commit/759e3abb7540cdcc39cccb2adef97d421e08f6f8
![image](https://cloud.githubusercontent.com/assets/1564068/5722209/9c4be350-9b3a-11e4-94cf-ba41f4277447.png)

**Comment by Joshua-Anderson** [comment] 2015-01-13 14:47
There is a setting somewhere to disable tagged builds,  can't remeber where at the moment. You are definitely tagging your builds properly, but for some reason Travis isn't building them. Might be a queung regression. Any ideas @BanzaiMan for why he isn't getting tagged builds?

**Comment by djindjic** [comment] 2015-01-13 14:55
I don't understand why would I want to disable tagged builds if I my original idea was to run them at travis.
I'm sure this is misunderstanding caused by my bad English :)

**Comment by BanzaiMan** [comment] 2015-01-13 17:19
v0.1.41 was deployed because you had `all_branches: true` (https://github.com/djindjic/forwardablejs/blob/b6d580eaca56c296b4c2d813163ddc57d0923a4e/.travis.yml#L16)

As mentioned in https://github.com/travis-ci/travis-ci/issues/1675#issuecomment-37851765, this is currently the known workaround of this issue. (This is a duplicate of that, obviously.)

**Comment by Joshua-Anderson** [comment] 2015-01-14 03:18
Yes @BanzaiMan, but he should still be getting tag builds. He isn't getting any tag builds at all anymore. That seems strange to me.

**Comment by djindjic** [comment] 2015-01-16 10:54
It would be extremely worth to support deployment of tagged builds on selected branch(es) instead of trigger it on for every (unsafe) branch which could be tagged accidentally of maliciously.

**Comment by BanzaiMan** [comment] 2015-09-03 12:55
I fixed https://github.com/travis-ci/travis-ci/issues/1675 a while back. I'm closing this optimistically.

**Closed by BanzaiMan** 2015-09-03 12:55 UTC
