### ISSUE TITLE
New Provider: Docker Registry

### ISSUE THREAD

**Issue by poulad** [travis-ci/dpl#867] opened 2018-09-18 15:51 UTC
### Feature :whale: 
A new provider to push docker images(build artifact) to a Docker registry such as hub.docker.com.
Multiple images can be published to different registries with Docker Hub being the default registry.

Here is what I have in mind as options:
```yml
deploy:
  docker:
    - source: local-foo
      target: foo/bar:edge
      registry: hub.docker.com # default
      user: foo
      password:
        - secure: ...
    - source: local-foo:latest
      target: bar/web:edge
      registry: registry.heroku.com
      user: foo
      password:
        - secure: ...
```

This should be easy to implement and in fact, I have already done so in JS. I have no experience with Ruby and cannot add it quickly myself.

Here is the script I use:

<https://github.com/Zevere/WebAPI-Borzoo/blob/110ba3d81af3468678dd52abd815d9b79700d32d/ci/deploy/deploy_docker_registry.js#L9-L12>

and the options (JSON) passed to it:
<https://github.com/Zevere/WebAPI-Borzoo/blob/110ba3d81af3468678dd52abd815d9b79700d32d/.travis.yml#L41>

**Comment by BanzaiMan** [comment] 2018-09-18 15:55
Thanks for opening the issue. Could you review your proposed YAML configuration? It is an array of 10 elements, which I don't think is what you meant.

**Comment by poulad** [comment] 2018-09-18 16:01
Thanks @BanzaiMan . I edited the proposed YAML configs.

**Comment by ankon** [comment] 2019-01-02 09:48
Please re-open: We're missing feedback from @BanzaiMan, but the issue isn't "solved already" nor is it "no longer applicable".

**Comment by chenrui333** [comment] 2019-04-06 19:57
Any update on this, right now I could use something like below:
https://medium.com/vaidikkapoor/managing-open-source-docker-images-on-docker-hub-using-travis-7fd33bc96d65

**Comment by mfrancis95** [comment] 2019-08-25 02:20
Also would like an update on this.

A provider that at least provides a shorthand for doing something like
`docker login -p $PASSWORD -u $USERNAME && docker push $TAG` would be helpful.

**Comment by svenfuchs** [comment] 2019-08-30 14:28
Here's a draft for a Docker provider based on the input on this ticket. I'm not sure it's capturing all the major use cases, and would love to get some feedback from you all:

https://github.com/travis-ci/dpl/pull/1091

**Comment by svenfuchs** [comment] 2019-08-30 14:35
I'm going to close this issue here. Let's continue the conversation on the PR. Feel free to re-open if needed though.

**Closed by svenfuchs** 2019-08-30 14:35 UTC
Labels: feature-request, important
