### ISSUE TITLE
dpl exits sucessfully despite failed deployment

### ISSUE THREAD

**Issue by falkorichter** [travis-ci/dpl#1008] opened 2019-06-25 14:20 UTC
I have a Rails app and a bad migration. My Procfile for heroku requires to run the migrations as part of the deployment:

```
web: bundle exec rails server

release: bundle exec rake db:migrate
```
This means, when `bundle exec rake db:migrate` the deployment is stopped and the currect deployment stays in place.

I was using dpl on gitlab to deploy my app:
```
dpl --provider=heroku --app=$application_name --api-key=$HEROKU_PRODUCTION_KEY
```
the deployment failed, I received an email, but dpl exited sucessfully and therefore gitlab assumed the deployment was successfull. That messed up the gitlab tracking of deployments. It needs to know if a deployment failed...

heroku cli reveals the failed deployments:
```
heroku releases                                                           
=== $ Releases - Current: v15
v15  Deploy 550a4bc9                                                                              falko@urbandrivestyle.com           2019/06/25 15:49:14 +0200 (~ 2m ago)
v14  Deploy 550a4bc9                                                                              falko@urbandrivestyle.com           2019/06/25 15:46:40 +0200 (~ 5m ago)
v13  Deploy b1bf438e                                                                              falko@urbandrivestyle.com           2019/06/25 15:42:10 +0200 (~ 9m ago)
v12  Deploy 550a4bc9 release command failed                                                       falko@urbandrivestyle.com           2019/06/25 15:33:12 +0200 (~ 18m ago)
v11  Deploy 550a4bc9 release command failed                                                       falko@urbandrivestyle.com           2019/06/25 15:01:14 +0200 (~ 50m ago)
v10  Deploy 550a4bc9 release command failed                                                       falko@urbandrivestyle.com           2019/06/25 14:59:41 +0200 (~ 52m ago)
```

```
dpl --provider=heroku --app=$application_name --api-key=$HEROKU_PRODUCTION_KEY --strategy=git
```
this shows the error but also returns sucessfull therefore gitlab doesn´t recognize the fail

<img width="1355" alt="Screenshot 2019-06-25 at 16 36 37" src="https://user-images.githubusercontent.com/50506/60107651-8dec2580-9767-11e9-9b6c-dd4c26f5db1c.png">

**Comment by BanzaiMan** [comment] 2019-06-25 17:04
Basically a duplicate of https://github.com/travis-ci/dpl/issues/143.

**Comment by svenfuchs** [comment] 2019-08-19 13:05
Thanks for reporting this @falkorichter.

I think this issue here can be closed as the problem wsa addressed in `master` (dpl v2). Please feel free to re-open if needed.

**Closed by svenfuchs** 2019-08-19 13:05 UTC
