### ISSUE TITLE
travis heroku

### ISSUE THREAD

**Issue by Mundukm** [travis-ci/dpl#653] opened 2017-06-13 21:35 UTC
after success build nothing happends, im new to travis, but i try everything to fix it without any results 
![heroku](https://user-images.githubusercontent.com/23221883/27105699-33636be4-5099-11e7-80be-09572a163812.PNG)

**Comment by BanzaiMan** [comment] 2017-06-13 21:58
Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/7904.

**Closed by BanzaiMan** 2017-06-13 21:58 UTC
