### ISSUE TITLE
dpl 1.9.0: deploy to github pages fails

### ISSUE THREAD

**Issue by caarlos0** [travis-ci/dpl#777] opened 2018-03-11 16:55 UTC
since dpl 1.9.0, my deploys to github pages are failing.

- [working deploy (dpl 1.8)](https://travis-ci.org/goreleaser/goreleaser/builds/350785724)
- [failing deploy (dpl 1.9)](https://travis-ci.org/goreleaser/goreleaser/builds/351004901)

error:

```
Couldn't push the build to github.com/goreleaser/goreleaser.github.io.git:master
failed to deploy
```

config:

```yaml
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: goreleaser/goreleaser.github.io
    local_dir: ./dist/goreleaser.github.io
    target_branch: master
    on:
      tags: true
      master: true
```

**Comment by BanzaiMan** [comment] 2018-03-11 16:58
Duplicate of travis-ci/travis-ci#9312.

**Closed by BanzaiMan** 2018-03-11 16:58 UTC

**Comment by caarlos0** [comment] 2018-03-11 17:03
sorry, somehow missed that one in the search

**Comment by BanzaiMan** [comment] 2018-03-11 17:21
Did you see #767 in your search?

**Comment by caarlos0** [comment] 2018-03-11 17:37
nope, I searched for open issues only, my mistake
