### ISSUE TITLE
Elasticbeanstalk missing CLI argument

### ISSUE THREAD

**Issue by devonhk** [travis-ci/dpl#823] opened 2018-06-13 20:25 UTC
**Description**
I can't deploy any elasticbeanstalk applications because the `dpl` cli won't accept the `--access-key-id` argument

**Repro steps**

0. Set env vars
1. `gem install dpl` (version: 1.9.7)
2. `$ dpl --provider=elasticbeanstalk --access-key-id="$AWS_ACCESS_KEY" --secret-access-key="$AWS_SECRET_KEY" --region="$AWS_DEPLOY_REGION"  --app="coregraf-api" --env="coregraf-api-develop"`

**Expected behavior**
dpl runs properly

**Actual behavior**
dpl craps out on unexpected argument:
`invalid option "--access-key-id="`

**Comment by joepvd** [comment] 2018-06-13 20:44
Thanks for reporting!

Could you , as a workaround, try again with the dashes replaces with underscores:

```
dpl --provider=elasticbeanstalk \
  --access_key_id="$AWS_ACCESS_KEY" \
  --secret_access_key="$AWS_SECRET_KEY" \
  --region="$AWS_DEPLOY_REGION" \
  --app="coregraf-api" \
  --env="coregraf-api-develop"
```

Wonder why the character translation does not seem to work:
https://github.com/travis-ci/dpl/blob/master/lib/dpl/cli.rb#L18

**Comment by pydo** [comment] 2018-06-13 21:10
Thanks for the quick reply.

To give you some context, I am running dpl in a docker container on a gitlab job runner. Here's the full output:
```
Pulling docker image ruby:latest ...
Using docker image sha256:857bc7ff918f67a8e74abd01dc02308040f7f7f9b99956a815c5a9cb6393f11f for ruby:latest ...
Running on runner-72989761-project-6239912-concurrent-0 via runner-72989761-srm-1528923911-d9365de9...
Cloning repository...
Cloning into '/builds/project/services'...
Checking out 15136ed6 as deploy-dev-on-merge...
Skipping Git submodules setup
Checking cache for default...
Downloading cache.zip from http://runners-cache-4-internal.gitlab.com:444/runner/project/6239912/default 
Successfully extracted cache
$ gem install dpl
Successfully installed dpl-1.9.7
1 gem installed
$ dpl --provider=elasticbeanstalk --secret_access_key="$AWS_SECRET_KEY" --access_key_id="$AWS_ACCESS_KEY"  --region="$AWS_DEPLOY_REGION"  --app="services-api" --env="services-api-develop"
invalid option "--secret_access_key="
ERROR: Job failed: exit code 1
```
I am still getting the error with the underscores. I will investigate to my end to make sure this isn't related to env vars not being set.

**Comment by pydo** [comment] 2018-06-13 21:21
I'm pretty sure my env vars were empty strings. I assumed `dpl` was at fault because of the `invalid option` error message.
I will close this issue once I confirm that the issue is on my end.

**Closed as completed** 2018-06-13 21:26 UTC
